export const GET_TOP_HEADLINES = 'GET_TOP_HEADLINES';
export const GET_NEWS_BY_TYPE = 'GET_NEWS_BY_TYPE';

export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PREFERENCE = 'UPDATE_PREFERENCE';
