export const GET_TOP_HEADLINES_SUCCESS = 'GET_TOP_HEADLINES_SUCCESS';
export const GET_NEWS_BY_TYPE_SUCCESS = 'GET_NEWS_BY_TYPE_SUCCESS';
export const GET_TOP_HEADLINES_FAIL = 'GET_TOP_HEADLINES_FAIL';
export const GET_NEWS_BY_TYPE_FAIL = 'GET_NEWS_BY_TYPE_FAIL';

export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PREFERENCE = 'UPDATE_PREFERENCE';
